### ISSUE TITLE
is there an example how to use this package

### ISSUE THREAD

**Issue by aalhadhoud** [MarcosNicolau/whatsapp-business-sdk#11]
Hello, 
the package works great. but i'm trying to understand how to use it with express.

I created a class named webhook.ts
```
const createWebHook = webhookClient.initWebhook({
    onStartListening: () => {
        console.log('Server started listening! webhook');
    },
    onTextMessageReceived: async (payload: any, contact: any) => {
        console.log('test');
    }
   
});
export default { createWebHook, webhookClient };
```

and then I imported the class in 
app.ts
`let webhook = require('./config/webhooks');`

but if I use 
```
router.post('/webhook', (req, res) => {});
```

it doesn't get triggered. and It goes straight to 
```
onTextMessageReceived: async (payload: any, contact: any) => {
        console.log('test');
    }
```

**Comment by MarcosNicolau** [comment]
Hi @aalhadhoud! :wave: 

Before anything, I am really glad you find this project useful. :smile: 
 
From what I understand,  you are creating a POST endpoint but it is not getting triggered, right? If that is so, I would guess that either you didn't change the `WebhookClient` path, which is `/webhook` by default, that is in case they share the same express app, or, if the client creates its own express app, you are not calling the endpoint from that app port.

If that is not what you meant, please correct me! :grin:

**Comment by aalhadhoud** [comment]
Hi @MarcosNicolau  thank you for your reply
ok let me explain what i'm doing exactly

here's my webhook.ts:
```
import { WABAClient, WABAErrorAPI, WebhookClient } from 'whatsapp-business';



const client = new WABAClient({
    accountId: 'xxxxxxxxxxxxxx',
    apiToken:
        'xxxxxxxxxxxxxxxxxxxxxxxx',
    phoneId: 'xxxxxxxxxxxxxxxxxxxxx'
});

const webhookClient = new WebhookClient({
    token: 'xxxxxxxxxxxxxxxxxxxxx',
    path: '/webhook'
});
const wabaClient = new WABAClient({
    accountId: 'xxxxxxxxxxx',
    phoneId: 'xxxxxxxxxx',
    apiToken:
        'xxxxxxxxxxxxxxxxxx'
});

const createWebHook = webhookClient.initWebhook({
    onStartListening: () => {
        console.log('Server started listening! webhook');
    },
    onTextMessageReceived: async (payload: any, contact: any) => {
        console.log('message received');
    }
   
});
export default { createWebHook, webhookClient, client };

```

Then I'm using it in in server.ts
```
const router = express();
let webhook = require('./config/webhooks');
router.set('webhook', webhook);
router.post('/webhook', (req, res) => {
        console.log('test2');
});
```

once I send a message from whatsapp my webhookClient gets trigger and it prints
message received 

but my router.post in the server.ts doesn't get trigger. though when i sendPOST request from postman it gets triggered and it prints test2

**Comment by MarcosNicolau** [comment]
I don't really understand what you are trying to do, why do you want to create another endpoint for the `/webhook`?

The `webhookClient` will create its own express app if you don't provide one, and will start listening as soon as you call `initWebhook`. Internally, it creates two endpoints with the provided `path` which defaults to `/webhook`, one is for subscribing and the other to receive the webhooks.

So, in your code, when you call `webhookClient.initWebhook` you are **creating a new server** that receives the webhooks calls.

**Comment by aalhadhoud** [comment]
How can I use `webhookClient.onTextMessageReceived` in server.ts ?

**Comment by MarcosNicolau** [comment]
`onTextMessageReceived` is a callback you provide when calling `webhookClient.initWebhook`. 

When you run `webhookClient.initWebhook` you start a server with the endpoints to listen to the webhook events. Based on the received event it will trigger the appropriate callback. For example, if someone sends you a text message then the callback `onTextMessageReceived` and `onMessageReceived` will be fired, if provided.

For further understanding, I'll suggest you check the code [here](https://github.com/MarcosNicolau/whatsapp-business-sdk/blob/main/src/webhooks/client.ts).

**Comment by MarcosNicolau** [comment]
@aalhadhoud I am closing this issue since I've just added a more detailed explanation. Please let me know if you were able to use the package.

Anyway, thank you for opening this issue and contributing, now the docs should be clearer!! :grinning:
