### ISSUE TITLE
Wrong type for WebhookMessage interactive

### ISSUE THREAD

**Issue by tecoad** [MarcosNicolau/whatsapp-business-sdk#26]
This is the current type for WebhookMessage interactive object:
```
    interactive?: {
        type: {
            /**
             * Sent when a customer clicks a button
             */
            button_reply?: {
                /**
                 *  Unique ID of a button
                 */
                id: string;
                title: string;
            };
            /**
             *  Sent when a customer selects an item from a list
             */
            list_reply?: {
                /**
                 * Unique ID of the selected list item
                 */
                id: string;
                title: string;
                description: string;
            };
        };
    };

```

However this is wrong. The button_reply object doesnt come nested in type.
Here is an example:

```
{
  "id": "wamid.HBgMNasdasdadUA",
  "from": "xxxxxxx",
  "type": "interactive",
  "context": {
    "id": "wamid.HBgMNTUzMTkxaYwOUM4NzBERjA1AA==",sdasdasdasd
    "from": "xxxxxxxx"
  },
  "timestamp": "1715709660",
  "interactive": {
    "type": "button_reply",
    "button_reply": {
      "id": "change",
      "title": "Change facts"
    }
  }
}
```

**Comment by MarcosNicolau** [comment]
mmm... seems that their docs are out of date or something

![image](https://github.com/MarcosNicolau/whatsapp-business-sdk/assets/76252340/ae2d943c-a699-467a-8c99-2ee7a6199c01)

**Comment by MarcosNicolau** [comment]
If you can confirm that you always get that response, I'll merge the fix!

**Comment by tecoad** [comment]
@MarcosNicolau can you provide the documentation link you are consulting from?
The one from [here](https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/payload-examples#reply-button) is exactly as I stated:

![Screen Shot 2024-05-14 at 16 23 58](https://github.com/MarcosNicolau/whatsapp-business-sdk/assets/2627749/6ec4e670-9d4b-4f7e-874b-d7e33b10bef4)

**Comment by MarcosNicolau** [comment]
Sure

https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/components#messages-object

**Comment by tecoad** [comment]
Meta is possibly the worst company to treat developers. Its the same website, just a few menu options below. 😔

But yes, i confirm, the structure I submitted in my PR and is in their [example](https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/payload-examples#reply-button)  is the correct one 100% of the time.

The one from the the link you provided is wrong.

Also, you can check there is [another TS lib](https://github.com/Secreto31126/whatsapp-api-js/blob/e8d001166c15d356f2cba8ad60c3e119e569f091/src/types.ts#L526C1-L527C1) that has these typings, you will see my PR is right.

**Comment by MarcosNicolau** [comment]
Yeah... it's impressive the fact that they don't provide us with an official sdk.

Alright so I am merging your fix, higher thanks! 😊

**Comment by tecoad** [comment]
@MarcosNicolau you are welcome!
I just noticed one test suite failed preventing publish. Couldnt reproduce locally. Any idea?

**Comment by MarcosNicolau** [comment]
Yeah... somehow the keys have expired, I'll make sure to renew them later.
