### ISSUE TITLE
product_items currently is mandatory 

### ISSUE THREAD

**Issue by tecoad** [MarcosNicolau/whatsapp-business-sdk#30]
Hi @MarcosNicolau,

Should product_items from InteractiveActionSection be mandatory only for product type messages?
As state [here](https://developers.facebook.com/docs/whatsapp/on-premises/reference/messages#interactive-object): Required for Multi-Product Messages.

Currently it is mandatory regardless of the message type...

**Comment by MarcosNicolau** [comment]
Yes you are right, I'll change it now.

**Comment by MarcosNicolau** [comment]
I've also realized that the `title` and `rows` fields should be optional as well...
