### ISSUE TITLE
Type error with "TemplateMessageButtonParameter"

### ISSUE THREAD

**Issue by JulianGarcia04** [MarcosNicolau/whatsapp-business-sdk#39]
I have a error with this type when i try to set button parameters.

![Screenshot 2024-07-30 at 9 50 44 AM](https://github.com/user-attachments/assets/2f850861-ca48-4150-8861-ec5507f28633)

And I try to change the type for a custom type...

![Screenshot 2024-07-30 at 9 53 35 AM](https://github.com/user-attachments/assets/5bce3ca0-3454-4090-845e-776b5962a1c2)

And it show this error.

Because "TemplateMessageButtonParameter" has a "GenerateMappedNever<TemplateMessageParameter>" being the problem 

![Screenshot 2024-07-30 at 9 54 53 AM](https://github.com/user-attachments/assets/c8209aff-e21f-4866-babe-8f7bc3995fe8)

And another problem is that when I try set a component with type equal to "button", the paramaters must be "TemplateMessageButtonParameter" and it doesn't change the type from "TemplateMessageParameter[]" to TemplateMessageButtonParameter[]", and I can't set a parameter with type equal "payload".

A image with more details of the problem...

![Screenshot 2024-07-30 at 10 16 24 AM](https://github.com/user-attachments/assets/0860fbce-0bab-488f-9e76-117f8af6384b)

Some solution ???

Thanks

**Comment by MarcosNicolau** [comment]
I'll try to take a look later on.

**Comment by MarcosNicolau** [comment]
I don't understand, is this library bug or it is something in your code?

**Comment by JulianGarcia04** [comment]
The bug is from library. Because when I set a component as button type then the parameter type must be change to TemplateMessageButtonParameter[].

**Comment by JulianGarcia04** [comment]
Another error is the TemplateMessageButtonParameter is bad. Because it is doing merge with GenerateMappedNever and the type parameter change to never.

**Comment by JulianGarcia04** [comment]
Problem solve in pull request #43

**Comment by tecoad** [comment]
Thanks for this @JulianGarcia04 , I just came across this issue yesterday when sending a template message by the first time :)
