### ISSUE TITLE
Missing support to geolocation header in template messages

### ISSUE THREAD

**Issue by JulianGarcia04** [MarcosNicolau/whatsapp-business-sdk#40]
When I wanna send template messages, the SDK doesn't support to templates with geolocation header

<img width="798" alt="Screenshot 2024-07-30 at 3 35 19 PM" src="https://github.com/user-attachments/assets/4384ac0c-a34c-4288-801e-76edc2271a26">

**Comment by MarcosNicolau** [comment]
Ok, I'll try to implement it asap. You can create a pr with the changes though.

**Comment by JulianGarcia04** [comment]
Requirement was added in pull request #43
