### ISSUE TITLE
Decouple sending messages and business number setup

### ISSUE THREAD

**Issue by lukas-becker0** [MarcosNicolau/whatsapp-business-sdk#41]
Since only the phone number id and the token are necessary to send messages 
I think it would make sense to decouple the client logic so that we have one client just for sending messages and another for the business number setup stuff.

In our case for example the service which is sending and receiving messages is not handling the phone number setup.

**Comment by MarcosNicolau** [comment]
Mmmm... I don't know about that, I'd prefer to avoid such breaking change. Do other libraries actually split that the logic?

**Comment by lukas-becker0** [comment]
Alright fair enough, this was just a suggestion, for my use case I'm currently using my own http client.

Although I think we could avoid breaking changes by keeping the existing client and just letting it use the e.g. `messaging` and `registration` clients.
